"""
DM-01 — Fingerprinting determinism and stability tests.

Verifies that fingerprints generated by utils.fingerprint_utils:
- Are deterministic: same inputs ⇒ same hash
- Are case/whitespace-insensitive for textual inputs
- Differ when discriminating fields change (column, threshold, rule)
- Have stable length (16 hex chars)
- Order-independent for list / dict inputs
"""
import sys
import os
import re

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest

from utils.fingerprint_utils import (
    generate_issue_fingerprint,
    generate_column_issue_fingerprint,
    generate_row_issue_fingerprint,
    generate_duplicate_issue_fingerprint,
    generate_pattern_issue_fingerprint,
    generate_syntactic_accuracy_fingerprint,
    generate_class_balance_fingerprint,
    generate_currentness_fingerprint,
    generate_diversity_fingerprint,
    generate_outlier_issue_fingerprint,
    generate_logical_consistency_fingerprint,
)


HEX16 = re.compile(r"^[0-9a-f]{16}$")


# ---------------------------------------------------------------------------
# Format invariants
# ---------------------------------------------------------------------------

class TestFingerprintFormat:
    """Every fingerprint produced is a 16-character lowercase hex string."""

    @pytest.mark.parametrize("fp", [
        generate_issue_fingerprint("completeness", "email"),
        generate_column_issue_fingerprint("completeness", "email", threshold=0.95),
        generate_row_issue_fingerprint("outliers", "age", [1, 2, 3]),
        generate_duplicate_issue_fingerprint(is_row_level=True),
        generate_pattern_issue_fingerprint("phone", r"\d{3}-\d{4}"),
        generate_syntactic_accuracy_fingerprint("email", "email"),
        generate_class_balance_fingerprint("target", "dominant_class"),
        generate_currentness_fingerprint("created_at", 30),
        generate_diversity_fingerprint("country", "missing_value"),
        generate_outlier_issue_fingerprint("price", "iqr", 1.5),
        generate_logical_consistency_fingerprint("a > b"),
    ])
    def test_fingerprint_is_16_hex_chars(self, fp):
        assert HEX16.match(fp), f"Expected 16 hex chars, got {fp!r}"


# ---------------------------------------------------------------------------
# Determinism: same input ⇒ same hash
# ---------------------------------------------------------------------------

class TestFingerprintDeterminism:

    def test_same_inputs_produce_same_hash(self):
        fp_a = generate_issue_fingerprint("completeness", "email")
        fp_b = generate_issue_fingerprint("completeness", "email")
        assert fp_a == fp_b

    def test_repeated_calls_are_stable(self):
        results = {
            generate_issue_fingerprint(
                "consistency", "phone", rule_key="pattern_check",
                extra_params={"pattern": r"\d{3}-\d{4}"},
            )
            for _ in range(50)
        }
        assert len(results) == 1, "Fingerprint changed across repeated calls"

    def test_case_insensitive_text_inputs(self):
        fp_lower = generate_issue_fingerprint("completeness", "email")
        fp_upper = generate_issue_fingerprint("COMPLETENESS", "EMAIL")
        fp_mixed = generate_issue_fingerprint("Completeness", "Email")
        assert fp_lower == fp_upper == fp_mixed

    def test_whitespace_is_stripped(self):
        fp_clean = generate_issue_fingerprint("completeness", "email")
        fp_spaced = generate_issue_fingerprint("  completeness  ", "  email  ")
        assert fp_clean == fp_spaced


# ---------------------------------------------------------------------------
# Discrimination: different inputs ⇒ different hash
# ---------------------------------------------------------------------------

class TestFingerprintDiscrimination:

    def test_different_issue_types_differ(self):
        fp_compl = generate_issue_fingerprint("completeness", "email")
        fp_uniq = generate_issue_fingerprint("uniqueness", "email")
        assert fp_compl != fp_uniq

    def test_different_columns_differ(self):
        fp_email = generate_issue_fingerprint("completeness", "email")
        fp_phone = generate_issue_fingerprint("completeness", "phone")
        assert fp_email != fp_phone

    def test_different_thresholds_differ(self):
        fp_95 = generate_column_issue_fingerprint("completeness", "email", threshold=0.95)
        fp_80 = generate_column_issue_fingerprint("completeness", "email", threshold=0.80)
        assert fp_95 != fp_80

    def test_different_rules_differ(self):
        fp_a = generate_issue_fingerprint("consistency", "phone", rule_key="rule_a")
        fp_b = generate_issue_fingerprint("consistency", "phone", rule_key="rule_b")
        assert fp_a != fp_b

    def test_row_vs_column_duplicate_differ(self):
        fp_row = generate_duplicate_issue_fingerprint(is_row_level=True)
        fp_col = generate_duplicate_issue_fingerprint(column_name="email", is_row_level=False)
        assert fp_row != fp_col


# ---------------------------------------------------------------------------
# Stability across irrelevant noise
# ---------------------------------------------------------------------------

class TestFingerprintNoiseTolerance:
    """metric_value, invalid_count, duplicate_count must NOT change the hash —
    they are informational and would otherwise cause every run to produce a
    different fingerprint for the same logical issue."""

    def test_column_fingerprint_ignores_metric_value(self):
        fp_a = generate_column_issue_fingerprint(
            "completeness", "email", metric_value=0.10, threshold=0.95,
        )
        fp_b = generate_column_issue_fingerprint(
            "completeness", "email", metric_value=0.30, threshold=0.95,
        )
        assert fp_a == fp_b

    def test_pattern_fingerprint_ignores_invalid_count(self):
        fp_a = generate_pattern_issue_fingerprint("phone", r"\d{3}-\d{4}", invalid_count=5)
        fp_b = generate_pattern_issue_fingerprint("phone", r"\d{3}-\d{4}", invalid_count=500)
        assert fp_a == fp_b

    def test_duplicate_fingerprint_ignores_count(self):
        fp_a = generate_duplicate_issue_fingerprint(is_row_level=True, duplicate_count=3)
        fp_b = generate_duplicate_issue_fingerprint(is_row_level=True, duplicate_count=99)
        assert fp_a == fp_b

    def test_outlier_fingerprint_rounds_factor(self):
        fp_a = generate_outlier_issue_fingerprint("price", "iqr", 1.50)
        fp_b = generate_outlier_issue_fingerprint("price", "iqr", 1.5001)
        assert fp_a == fp_b


# ---------------------------------------------------------------------------
# Order-independence for list/dict inputs
# ---------------------------------------------------------------------------

class TestFingerprintOrderIndependence:

    def test_row_indices_order_does_not_matter(self):
        fp_sorted = generate_row_issue_fingerprint("outliers", "price", [1, 2, 3, 4, 5])
        fp_unsorted = generate_row_issue_fingerprint("outliers", "price", [5, 3, 1, 4, 2])
        assert fp_sorted == fp_unsorted

    def test_extra_params_order_does_not_matter(self):
        fp_a = generate_issue_fingerprint(
            "consistency", "phone", rule_key="pattern_check",
            extra_params={"a": 1, "b": 2, "c": 3},
        )
        fp_b = generate_issue_fingerprint(
            "consistency", "phone", rule_key="pattern_check",
            extra_params={"c": 3, "a": 1, "b": 2},
        )
        assert fp_a == fp_b


# ---------------------------------------------------------------------------
# Empty/None handling
# ---------------------------------------------------------------------------

class TestFingerprintEdgeCases:

    def test_none_column_does_not_crash(self):
        fp = generate_issue_fingerprint("uniqueness", column_name=None)
        assert HEX16.match(fp)

    def test_empty_extra_params_equivalent_to_none(self):
        fp_none = generate_issue_fingerprint("completeness", "email")
        fp_empty = generate_issue_fingerprint("completeness", "email", extra_params=None)
        assert fp_none == fp_empty

    def test_row_indices_truncation_preserves_distinct_hash(self):
        """When >max_rows are passed, the count is included in extra_params
        so two issues with different cardinality stay distinguishable."""
        rows_small = list(range(15))
        rows_big = list(range(150))
        fp_small = generate_row_issue_fingerprint("outliers", "price", rows_small)
        fp_big = generate_row_issue_fingerprint("outliers", "price", rows_big)
        assert fp_small != fp_big
