"""empty message

Revision ID: dd685e7e770a
Revises: d762936f6042
Create Date: 2026-03-29 23:36:22.412538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd685e7e770a'
down_revision = 'd762936f6042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analysis_runs_project_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('analysis_runs_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'])

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('sensitive_columns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_latest',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_datasets_is_latest'))
        batch_op.drop_index(batch_op.f('ix_datasets_parent_dataset_id'))
        batch_op.drop_constraint(batch_op.f('fk_datasets_parent_dataset_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('datasets_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['parent_dataset_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('evaluations_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'])

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_issues_fingerprint'))
        batch_op.create_index(batch_op.f('ix_issues_fingerprint'), ['fingerprint'], unique=False)

    with op.batch_alter_table('metric_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('metric_templates_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('quality_gates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quality_gates_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_gates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quality_gates_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('metric_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('metric_templates_owner_id_fkey'), 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_fingerprint'))
        batch_op.create_index(batch_op.f('idx_issues_fingerprint'), ['fingerprint'], unique=False)

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evaluations_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('datasets_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_datasets_parent_dataset_id'), 'datasets', ['parent_dataset_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_datasets_parent_dataset_id'), ['parent_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_is_latest'), ['is_latest'], unique=False)
        batch_op.alter_column('is_latest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('sensitive_columns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analysis_runs_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('analysis_runs_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
